description = "Ubi 8 base image with buildpacks for Node.js, Java, Quarkus and Procfile"

[[buildpacks]]
  uri = "docker://docker.io/paketocommunity/ubi-java-buildpack:0.1.1"
  version = "0.1.1"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/quarkus:0.4.1"
  version = "0.4.1"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java:17.5.0"
  version = "17.5.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/nodejs:7.1.3"
  version = "7.1.3"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.10.2"
  version = "5.10.2"

[[extensions]]
  id = "paketo-community/ubi-java-extension"
  uri = "docker://docker.io/paketocommunity/ubi-java-extension:0.2.0"
  version = "0.2.0"

[[extensions]]
  id = "paketo-buildpacks/ubi-nodejs-extension"
  uri = "docker://docker.io/paketobuildpacks/ubi-nodejs-extension:1.1.1"
  version = "1.1.1"

[lifecycle]
  version = "0.20.5"

[[order]]

  [[order.group]]
    id = "paketo-community/ubi-java-buildpack"
    version = "0.1.1"

  [[order.group]]
    id = "paketo-buildpacks/quarkus"
    optional = true
    version = "0.4.1"

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "17.5.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "7.1.3"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.10.2"

[[order-extensions]]

  [[order-extensions.group]]
    id = "paketo-community/ubi-java-extension"
    version = "0.2.0"

  [[order-extensions.group]]
    id = "paketo-buildpacks/ubi-nodejs-extension"
    version = "1.1.1"

[stack]
  build-image = "docker.io/paketocommunity/build-ubi-base:0.0.95"
  id = "io.buildpacks.stacks.ubi8"
  run-image = "index.docker.io/paketocommunity/run-ubi-base:latest"
  run-image-mirrors = []
