description = "Ubi 8 base image with buildpacks for Node.js"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/nodejs:1.8.0"
  version = "1.8.0"

[lifecycle]
  version = "0.17.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "1.8.0"

[stack]
  build-image = "docker.io/paketocommunity/build-ubi-base:0.0.1"
  id = "io.buildpacks.stacks.ubi8"
  run-image = "index.docker.io/paketocommunity/run-ubi-base:latest"
  run-image-mirrors = []
