description = "Ubi 8 base image with buildpacks for Node.js, Java, Quarkus and Procfile"

[[buildpacks]]
  uri = "docker://docker.io/paketocommunity/ubi-java-buildpack:0.1.1"
  version = "0.1.1"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/quarkus:0.5.0"
  version = "0.5.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java:18.4.0"
  version = "18.4.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/nodejs:7.4.0"
  version = "7.4.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.11.0"
  version = "5.11.0"

[[extensions]]
  id = "paketo-community/ubi-java-extension"
  uri = "docker://docker.io/paketocommunity/ubi-java-extension:0.2.0"
  version = "0.2.0"

[[extensions]]
  id = "paketo-buildpacks/ubi-nodejs-extension"
  uri = "docker://docker.io/paketobuildpacks/ubi-nodejs-extension:1.2.2"
  version = "1.2.2"

[lifecycle]
  version = "0.20.7"

[[order]]

  [[order.group]]
    id = "paketo-community/ubi-java-buildpack"
    version = "0.1.1"

  [[order.group]]
    id = "paketo-buildpacks/quarkus"
    optional = true
    version = "0.5.0"

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "18.4.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "7.4.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.11.0"

[[order-extensions]]

  [[order-extensions.group]]
    id = "paketo-community/ubi-java-extension"
    version = "0.2.0"

  [[order-extensions.group]]
    id = "paketo-buildpacks/ubi-nodejs-extension"
    version = "1.2.2"

[stack]
  build-image = "docker.io/paketobuildpacks/build-ubi8-base:0.0.109"
  id = "io.buildpacks.stacks.ubi8"
  run-image = "index.docker.io/paketobuildpacks/run-ubi8-base:latest"
  run-image-mirrors = []
