description = "Ubi 8 base image with buildpacks for Node.js, Java, Quarkus and Procfile"

[[buildpacks]]
  uri = "docker://docker.io/paketocommunity/ubi-java-buildpack:0.1.0"
  version = "0.1.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/quarkus:0.2.5"
  version = "0.2.5"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java:12.0.0"
  version = "12.0.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/nodejs:2.2.0"
  version = "2.2.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.6.9"
  version = "5.6.9"

[[extensions]]
  id = "paketo-community/ubi-java-extension"
  uri = "docker://docker.io/paketocommunity/ubi-java-extension:0.1.1"
  version = "0.1.1"

[[extensions]]
  id = "paketo-community/ubi-nodejs-extension"
  uri = "docker://docker.io/paketocommunity/ubi-nodejs-extension:0.3.1"
  version = "0.3.1"

[lifecycle]
  version = "0.18.5"

[[order]]

  [[order.group]]
    id = "paketo-community/ubi-java-buildpack"
    version = "0.1.0"

  [[order.group]]
    id = "paketo-buildpacks/quarkus"
    optional = true
    version = "0.2.5"

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "12.0.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "2.2.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.6.9"

[[order-extensions]]

  [[order-extensions.group]]
    id = "paketo-community/ubi-java-extension"
    version = "0.1.1"

  [[order-extensions.group]]
    id = "paketo-community/ubi-nodejs-extension"
    version = "0.3.1"

[stack]
  build-image = "docker.io/paketocommunity/build-ubi-base:0.0.40"
  id = "io.buildpacks.stacks.ubi8"
  run-image = "index.docker.io/paketocommunity/run-ubi-base:latest"
  run-image-mirrors = []
