description = "Ubi 8 base image with buildpacks for Node.js and Java"

[[buildpacks]]
  uri = "docker://docker.io/paketocommunity/ubi-java-buildpack:0.1.0"
  version = "0.1.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/quarkus:0.2.4"
  version = "0.2.4"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java:10.4.0"
  version = "10.4.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/nodejs:2.0.0"
  version = "2.0.0"

[[extensions]]
  id = "paketo-community/ubi-java-extension"
  uri = "docker://docker.io/paketocommunity/ubi-java-extension:0.1.1"
  version = "0.1.1"

[[extensions]]
  id = "paketo-community/ubi-nodejs-extension"
  uri = "docker://docker.io/paketocommunity/ubi-nodejs-extension:0.1.0"
  version = "0.1.0"

[lifecycle]
  version = "0.18.2"

[[order]]

  [[order.group]]
    id = "paketo-community/ubi-java-buildpack"
    version = "0.1.0"

  [[order.group]]
    id = "paketo-buildpacks/quarkus"
    optional = true
    version = "0.2.4"

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "10.4.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "2.0.0"

[[order-extensions]]

  [[order-extensions.group]]
    id = "paketo-community/ubi-java-extension"
    version = "0.1.1"

  [[order-extensions.group]]
    id = "paketo-community/ubi-nodejs-extension"
    version = "0.1.0"

[stack]
  build-image = "docker.io/paketocommunity/build-ubi-base:0.0.20"
  id = "io.buildpacks.stacks.ubi8"
  run-image = "index.docker.io/paketocommunity/run-ubi-base:latest"
  run-image-mirrors = []
